#!/bin/bash

set -eu

# refs: https://stackoverflow.com/questions/7516455/sed-extract-version-number-from-string-only-version-without-other-numbers
SWIFT_VERSION=$(docker run ${IMAGE_NAME} swift --version | grep 'Swift version' | sed 's/[^0-9.]*\([0-9.]*\).*/\1/')

echo $SWIFT_VERSION
echo $(echo $SWIFT_VERSION | sed -E 's/([0-9]*)\.([0-9]*)\.([0-9]*)/\1.\2/g')
echo $(echo $SWIFT_VERSION | sed -E 's/([0-9]*)\.([0-9]*)\.([0-9]*)/\1/g')
