#!/bin/bash

set -eu

function push_tag() {
    docker tag "${IMAGE_NAME}" "${DOCKER_REPO}:$1"
    docker push "${DOCKER_REPO}:$1"
}

# refs: https://stackoverflow.com/questions/7516455/sed-extract-version-number-from-string-only-version-without-other-numbers
SWIFT_VERSION=$(docker run ${IMAGE_NAME} swift --version | grep 'Swift version' | sed 's/[^0-9.]*\([0-9.]*\).*/\1/')
SWIFT_VERSION_MAJOR_MINOR=$(echo $SWIFT_VERSION | sed -E 's/([0-9]*)\.([0-9]*)\.([0-9]*)/\1.\2/g')
SWIFT_VERSION_MAJOR=$(echo $SWIFT_VERSION | sed -E 's/([0-9]*)\.([0-9]*)\.([0-9]*)/\1.\2/g')

push_tag "${SWIFT_VERSION}-${SOURCE_BRANCH}"
push_tag "${SWIFT_VERSION_MAJOR_MINOR}"
push_tag "${SWIFT_VERSION_MAJOR}"

if [[ "${SOURCE_BRANCH}" == "main" ]]; then
    push_tag "${SWIFT_VERSION}"
    push_tag "${SWIFT_VERSION_MAJOR_MINOR}"
    push_tag "${SWIFT_VERSION_MAJOR}"
fi
