name: DockerHub
on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/docker_hub.yml'
      - '.github/workflows/validate.yml'
      - '**/Dockerfile'
  schedule:
    - cron: 0 15 * * 6
env:
  DOCKER_USER: 41772ki
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  DOCKER_REPO: swift-mint
jobs:
  build:
    strategy:
      matrix:
        swift_version: [latest, 5.3.2, 5.3.1, 5.3, 5.2.5, 5.2.4, 5.2.3, 5.2.2, 5.2.1, 5.1.5, 5.1.4, 5.1.3, 5.1.2, 5.1.1, 5.1]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      run: docker build -t "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}" --build-arg "SWIFT_VERSION=${{ matrix.swift_version }}" .
    - name: Print Versions
      run: |
        docker run "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}" swift --version
        docker run "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}" mint version
    - name: Login DockerHub
      run: echo "${DOCKER_PASS}" | docker login -u ${DOCKER_USER} --password-stdin
    - name: Push DockerHub
      run: |
        IMAGE_NAME=$(docker images "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}" -q)
        SWIFT_VERSION=$(docker run "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}" swift --version | grep 'Swift version' | awk '{ print $NF }' | sed 's/[^0-9.]*\([0-9.]*\).*/\1/')
        scripts/docker_push_tag.sh "$IMAGE_NAME" "${DOCKER_USER}/${DOCKER_REPO}" "$SWIFT_VERSION"

        if [ "${{ matrix.swift_version }}" == 'latest' ]; then
          scripts/docker_push_tag.sh "$IMAGE_NAME" "${DOCKER_USER}/${DOCKER_REPO}" "latest"

          SWIFT_VERSION_MAJOR_MINOR=$(echo $SWIFT_VERSION | sed -E 's/([0-9]*)\.([0-9]*)\.([0-9]*)/\1.\2/g')
          scripts/docker_push_tag.sh "$IMAGE_NAME" "${DOCKER_USER}/${DOCKER_REPO}" "$SWIFT_VERSION_MAJOR_MINOR"

          SWIFT_VERSION_MAJOR=$(echo $SWIFT_VERSION | sed -E 's/([0-9]*)\.([0-9]*)\.([0-9]*)/\1/g')
          scripts/docker_push_tag.sh "$IMAGE_NAME" "${DOCKER_USER}/${DOCKER_REPO}" "$SWIFT_VERSION_MAJOR"
        fi
