name: DockerHub
on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/docker_hub.yml'
      - '**/Dockerfile'
env:
  DOCKER_USER: 41772ki
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  DOCKER_REPO: swift-mint
jobs:
  build:
    strategy:
      matrix:
        swift_version: [latest]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      run: docker build -t "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}" swift-${{ matrix.swift_version }}
    - name: Login DockerHub
      run: echo "${DOCKER_PASS}" | docker login -u ${DOCKER_USER} --password-stdin
    - name: Push DockerHub (latest)
      if: matrix.swift_version == 'latest'
      run: docker push "${DOCKER_USER}/${DOCKER_REPO}:latest"
    - name: Push DockerHub
      run: |
        function push_tag() {
          IMAGE_NAME=$(docker images "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}" -q)
          docker tag $IMAGE_NAME "${DOCKER_USER}/${DOCKER_REPO}:$1"
          docker push "${DOCKER_USER}/${DOCKER_REPO}:$1"
        }
        SWIFT_VERSION=$(docker run "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}" swift --version | grep 'Swift version' | sed 's/[^0-9.]*\([0-9.]*\).*/\1/')
        SWIFT_VERSION_MAJOR_MINOR=$(echo $SWIFT_VERSION | sed -E 's/([0-9]*)\.([0-9]*)\.([0-9]*)/\1.\2/g')
        SWIFT_VERSION_MAJOR=$(echo $SWIFT_VERSION | sed -E 's/([0-9]*)\.([0-9]*)\.([0-9]*)/\1/g')
        push_tag $SWIFT_VERSION
        push_tag $SWIFT_VERSION_MAJOR_MINOR
        push_tag $SWIFT_VERSION_MAJOR
