name: Validate Dockerfile
on: 
  pull_request:
    paths:
      - '.github/workflows/docker_hub.yml'
      - '.github/workflows/validate.yml'
      - '**/Dockerfile'
env:
  DOCKER_USER: 41772ki
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  DOCKER_REPO: swift-mint
jobs:
  validate:
    strategy:
      matrix:
        swift_version: [latest, 5.3.1, 5.3, 5.2.5, 5.2.4, 5.2.3, 5.2.2, 5.2.1, 5.1.5, 5.1.4, 5.1.3, 5.1.2, 5.1.1, 5.1]
        mint_revision: [master]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker image
      run: docker build -t "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}-${{ matrix.mint_revision }}" --build-arg "MINT_REVISION=${{ matrix.mint_revision }}" --build-arg "SWIFT_VERSION=${{ matrix.swift_version }}" .
    - name: Validate Swift version
      run: docker run "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}-${{ matrix.mint_revision }}" swift --version
    - name: Validate Mint version
      run: docker run "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}-${{ matrix.mint_revision }}" mint version
