name: Validate Dockerfile
on: 
  pull_request:
    paths:
      - '.github/workflows/docker_hub.yml'
      - '.github/workflows/validate.yml'
      - '**/Dockerfile'
env:
  DOCKER_USER: 41772ki
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  DOCKER_REPO: swift-mint
jobs:
  generate-matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          matrix=$(cat versions.json | jq -c .)
          echo "::set-output name=matrix::$matrix"

  validate:
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}-${{ matrix.mint_revision }}" --build-arg "MINT_REVISION=${{ matrix.mint_revision }}" --build-arg "SWIFT_VERSION=${{ matrix.swift_version }}" .
    - name: Validate Swift version
      run: docker run "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}-${{ matrix.mint_revision }}" swift --version
    - name: Validate Mint version
      run: docker run "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}-${{ matrix.mint_revision }}" mint version
