name: Validate Dockerfile
on: 
  pull_request:
    paths:
      - '.github/workflows/docker_hub.yml'
      - '.github/workflows/validate.yml'
      - '**/Dockerfile'
      - '.github/matrix.json'
env:
  DOCKER_USER: 41772ki
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
  DOCKER_REPO: swift-mint
jobs:
  generate-matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: |
          matrix=$(cat .github/matrix.json | jq -c .)
          echo "::set-output name=matrix::$matrix"

  validate:
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        push: false
        load: true
        tags: ${{ env.DOCKER_USER }}/${{ env.DOCKER_REPO }}:${{ matrix.swift_version }}-${{ matrix.mint_revision }}
        build-args: |
          SWIFT_VERSION=${{ matrix.swift_version }}
          MINT_REVISION=${{ matrix.mint_revision }}
    - name: Validate Swift version
      id: swift-version
      run: |
        SWIFT_VERSION=$(docker run "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}-${{ matrix.mint_revision }}" swift --version)
        echo $SWIFT_VERSION
        echo "::set-output name=value::$SWIFT_VERSION"
    - name: Validate Mint version
      id: mint-version
      run: |
        MINT_VERSION=$(docker run "${DOCKER_USER}/${DOCKER_REPO}:${{ matrix.swift_version }}-${{ matrix.mint_revision }}" mint version)
        echo $MINT_VERSION
        echo "::set-output name=value::$MINT_VERSION"
    - name: Comment to PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SWIFT_VERSION: ${{ steps.swift-version.outputs.value }}
        MINT_VERSION: ${{ steps.mint-version.outputs.value }}
      run: |
        gh pr comment -b "
        Swift version: $SWIFT_VERSION
        Mint version: $MINT_VERSION
        " "${{ github.event.pull_request.html_url }}"